#!/usr/bin/env python3
# /// script
# requires-python = ">=3.9"
# ///
"""Render assets/og.svg — the share card — from composers.json.

The card is a REAL rendering of the dataset, not a logo on a colored rectangle: same axes, same
radius exponent, same lifespan ramp as chart.js. Two reasons that is worth a script instead of a
hand-drawn SVG. It cannot go stale — rebuild the data and the preview follows — and the thing
someone sees in a chat thread is the thing they get when they tap.

Pipeline:  scripts/make-og-svg.py  ->  assets/og.svg  ->  scripts/make-og.sh  ->  assets/og.png
The PNG is what index.html references; scrapers reject SVG and relative URLs alike.

Keep the constants below in agreement with chart.js — they are duplicated, not shared, because
the app must not ship a build step and this must not ship a JS runtime.
"""
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

W, H = 1200, 630
PLOT = {"x": 520, "y": 96, "w": 608, "h": 446}      # chart panel, right of the title block
X_DOMAIN = (1700, 1992)
Y_DOMAIN = (0.85, 170)
LIFE = (20, 72, 104)                                 # min / median / max completed lifespan
R_RANGE = (2.4, 26)
R_EXP = 0.35

BG, PANEL, INK, MUTED, GRID = "#14161a", "#191c21", "#eceef0", "#9aa3a8", "#2b313a"
SHORT, MID, LONG, LIVING = "#f0a44a", "#7e8079", "#b3a4dd", "#8e979c"

# Labelled by hand: the point of the card is that a reader recognizes a name in it, and "top 6 by
# pageviews" would print Beethoven/Mozart/Tchaikovsky — famous, but not famous *as quartet
# composers*, which is what the chart is about. The four most prolific sit almost on top of each
# other (Cambini, Boccherini and Haydn are all born within 14 years and all in the top band), so
# placement is explicit rather than automatic: (name, anchor, dx, dy) around the dot.
VIEWS_MONTH = ""

LABELS = [
    ("Giuseppe Cambini",     "middle", 0, "above"),
    ("Luigi Boccherini",     "start",  9, "beside"),
    ("Joseph Haydn",         "middle", 0, "below"),
    ("Ludwig van Beethoven", "middle", 0, "above"),
    ("Bela Bartok",          "middle", 0, "above"),
    ("Dmitri Shostakovich",  "middle", 0, "above"),
]


def hexrgb(c):
    return tuple(int(c[i:i + 2], 16) for i in (1, 3, 5))


def mix(a, b, t):
    ra, rb = hexrgb(a), hexrgb(b)
    return "#%02x%02x%02x" % tuple(round(ra[i] + (rb[i] - ra[i]) * t) for i in range(3))


def color(lifespan, living):
    if living:
        return None                                  # open circle, same as the app
    lo, mid, hi = LIFE
    v = max(lo, min(hi, lifespan))
    return mix(SHORT, MID, (v - lo) / (mid - lo)) if v <= mid else mix(MID, LONG, (v - mid) / (hi - mid))


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def main():
    with open(os.path.join(ROOT, "composers.json")) as f:
        data = json.load(f)
    rows = data["rows"]
    max_views = max(r[4] for r in rows) or 1
    global VIEWS_MONTH
    VIEWS_MONTH = data["meta"]["views_month"]

    def sx(year):
        return PLOT["x"] + (year - X_DOMAIN[0]) / (X_DOMAIN[1] - X_DOMAIN[0]) * PLOT["w"]

    def sy(q):
        lo, hi = math.log10(Y_DOMAIN[0]), math.log10(Y_DOMAIN[1])
        return PLOT["y"] + PLOT["h"] - (math.log10(q) - lo) / (hi - lo) * PLOT["h"]

    def sr(v):
        return R_RANGE[0] + (R_RANGE[1] - R_RANGE[0]) * (v / max_views) ** R_EXP

    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}">',
           '  <!-- GENERATED by scripts/make-og-svg.py — do not hand-edit; rerun the script. -->',
           f'  <rect width="{W}" height="{H}" fill="{BG}"/>',
           f'  <rect x="{PLOT["x"] - 26}" y="{PLOT["y"] - 26}" width="{PLOT["w"] + 52}" '
           f'height="{PLOT["h"] + 52}" rx="16" fill="{PANEL}"/>']

    for year in range(1750, 2000, 50):
        out.append(f'  <line x1="{sx(year):.1f}" y1="{PLOT["y"]}" x2="{sx(year):.1f}" '
                   f'y2="{PLOT["y"] + PLOT["h"]}" stroke="{GRID}" stroke-width="1"/>')
        out.append(f'  <text x="{sx(year):.1f}" y="{PLOT["y"] + PLOT["h"] + 26}" fill="{MUTED}" '
                   f'font-family="system-ui,sans-serif" font-size="17" text-anchor="middle">{year}</text>')
    for q in (1, 3, 10, 30, 100):
        out.append(f'  <line x1="{PLOT["x"]}" y1="{sy(q):.1f}" x2="{PLOT["x"] + PLOT["w"]}" '
                   f'y2="{sy(q):.1f}" stroke="{GRID}" stroke-width="1"/>')
        out.append(f'  <text x="{PLOT["x"] - 12}" y="{sy(q) + 6:.1f}" fill="{MUTED}" '
                   f'font-family="system-ui,sans-serif" font-size="17" text-anchor="end">{q}</text>')

    for name, birth, life, quartets, views, living in sorted(rows, key=lambda r: -r[4]):
        cx, cy, r = sx(birth), sy(quartets), sr(views)
        fill = color(life, living)
        if fill is None:
            out.append(f'  <circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r:.1f}" fill="none" '
                       f'stroke="{LIVING}" stroke-width="1.4" opacity=".9"/>')
        else:
            out.append(f'  <circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r:.1f}" fill="{fill}" '
                       f'stroke="{PANEL}" stroke-width="1" opacity=".92"/>')

    by_name = {r[0]: r for r in rows}
    for name, anchor, dx, where in LABELS:
        r = by_name.get(name)
        if not r:
            print("WARNING: label %r is not in the data — skipped" % name, file=sys.stderr)
            continue
        cx, cy, rad = sx(r[1]), sy(r[3]), sr(r[4])
        tx = cx + (dx + (rad if dx > 0 else -rad) if where == "beside" else 0)
        ty = {"above": cy - rad - 9, "below": cy + rad + 21}.get(where, cy + 6)
        # Halo painted in the PAGE background, not the panel's: a "beside" label can hang off the
        # panel's left edge, and a panel-colored halo would show as a visible smear out there.
        out.append(f'  <text x="{tx:.1f}" y="{ty:.1f}" fill="{INK}" '
                   f'font-family="system-ui,sans-serif" font-size="18" font-weight="600" '
                   f'text-anchor="{anchor}" stroke="{BG}" stroke-width="4" '
                   f'paint-order="stroke" stroke-linejoin="round">{esc(name)}</text>')

    out += [
        f'  <text x="72" y="192" fill="{INK}" font-family="Georgia,serif" font-size="54" '
        f'font-weight="700">String Quartet</text>',
        f'  <text x="72" y="254" fill="{INK}" font-family="Georgia,serif" font-size="54" '
        f'font-weight="700">Composers</text>',
        f'  <text x="72" y="316" fill="{MUTED}" font-family="system-ui,sans-serif" font-size="24">'
        f'{len(rows)} composers, {min(r[1] for r in rows)}–{max(r[1] for r in rows)}.</text>',
        f'  <text x="72" y="350" fill="{MUTED}" font-family="system-ui,sans-serif" font-size="24">'
        f'Birth year × quartets written.</text>',
        f'  <text x="72" y="384" fill="{MUTED}" font-family="system-ui,sans-serif" font-size="24">'
        f'Size = page views, {VIEWS_MONTH}.</text>',
        f'  <rect x="72" y="410" width="220" height="12" rx="2" fill="url(#ramp)"/>',
        f'  <text x="72" y="448" fill="{MUTED}" font-family="system-ui,sans-serif" font-size="17">'
        f'short life</text>',
        f'  <text x="292" y="448" fill="{MUTED}" font-family="system-ui,sans-serif" font-size="17" '
        f'text-anchor="end">long life</text>',
        f'  <text x="72" y="540" fill="{MUTED}" font-family="system-ui,sans-serif" font-size="18">'
        f'jsundram.github.io/quartet-composers</text>',
        '  <defs><linearGradient id="ramp" x1="0" x2="1">'
        f'<stop offset="0" stop-color="{SHORT}"/><stop offset=".5" stop-color="{MID}"/>'
        f'<stop offset="1" stop-color="{LONG}"/></linearGradient></defs>',
        '</svg>',
    ]

    path = os.path.join(ROOT, "assets", "og.svg")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote assets/og.svg (%d composers, %d bytes)" % (len(rows), os.path.getsize(path)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
